PROGS = hello.c
PROGS = comm.c
PROGS = matmul.c
# PROGS = mergesort.c


BOOTLOADER = parallel-install


# set to 1 if you want to run.
RUN=1

L := $(CS140E_2025_FINAL_PATH)/libpi/

include $(CS140E_2025_FINAL_PATH)/libpi/mk/Makefile.template-fixed