PROGS = hello.c
PROGS = comm.c
# PROGS = matmul.c
# PROGS = matmul-hard.c
# PROGS = gpio_int.c
# PROGS = mergesort.c
PROGS = fmpi_async.c

BOOTLOADER = parallel-install


# set to 1 if you want to run.
RUN=1

L := $(CS140E_2025_FINAL_PATH)/libpi/

include $(CS140E_2025_FINAL_PATH)/libpi/mk/Makefile.template-fixed