# PROGS = fmpi-test.c
PROGS = fmpi-async.c


BOOTLOADER = parallel-install


# set to 1 if you want to run.
RUN=1

NUM_PI = 2

L := $(CS140E_2025_FINAL_PATH)/libpi/

include $(CS140E_2025_FINAL_PATH)/libpi/mk/Makefile.template-fixed
# include $(CS140E_2025_FINAL_PATH)/libpi/mk/Makefile.template-v3