PROGS = render.c

BOOTLOADER = 4pi-install

NUM_PI = 1

# set to 1 if you want to run.
RUN=1

L := $(CS140E_2025_FINAL_PATH)/libpi/

include $(CS140E_2025_FINAL_PATH)/libpi/mk/Makefile.template-fixed
# include $(CS140E_2025_FINAL_PATH)/libpi/mk/Makefile.template-v3